source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '~> 4.1.5'
gem 'railties', '~> 4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0'
gem 'spring'
gem 'capistrano-rails'
gem 'zurb-foundation'
gem 'foundation-rails'
gem 'simple_form'
gem 'devise'
gem 'execjs'
